### ISSUE TITLE
API improvement

### ISSUE THREAD

**Issue by Arbaz23** [0xb4dc0d3x/Registration#1]
Hello, can i add more rest methods to the api?

**Comment by 0xb4dc0d3x** [comment]
yea, improve the REST method of this API's

**Comment by Arbaz23** [comment]
thks, @0xb4dc0d3x i think i gonna add stream/subject on the controller to then be able to add students, subjects in a stream etc

**Comment by 0xb4dc0d3x** [comment]
thank you @Arbaz23
