### ISSUE TITLE
Front End 

### ISSUE THREAD

**Issue by Arbaz23** [0xb4dc0d3x/Registration#2]
Hello, can i developp the front end part for this api ?

**Comment by 0xb4dc0d3x** [comment]
Hi @Arbaz23, yea you can develop the front end part for this api, thank you for contributing

**Comment by Arbaz23** [comment]
hello, you can run this and tell me if it's good

**Comment by 0xb4dc0d3x** [comment]
hello, I merged your front-end, but in case I can't register new student due to Status Code: 403,
then I use Postman to check APIs are working or not, I find out all API are working well.

I think there is a problem in front-end.

**Comment by Arbaz23** [comment]
did you install all react JS dependencies ? 
or try to separate the api and the front folder and launch them separately

**Comment by 0xb4dc0d3x** [comment]
I installed everything that it needs.

**Comment by 0xb4dc0d3x** [comment]
- Frontend
